### ISSUE TITLE
set fact firefox_profile is broken for jailed firefox

### ISSUE THREAD

**Issue by petRUShka** [alzadude/ansible-firefox#3]
If your firefox is [jailed](https://firejail.wordpress.com/) set fact `firefox_profile` is broken.

Possible solution is to use following code:

```
- name: Ensure profile exists
  shell: firefox -no-remote -CreateProfile default 2>&1 | grep Success | sed "s/.*created profile '.\+' at '\(.\+\)'/\1/"
  register: create_profile
  changed_when: grep_profile.rc > 0

- set_fact:
    firefox_profile: "{{ create_profile.stdout | dirname }}"
```
